baseURL = "https://hindungwang.github.io/"
defaultContentLanguage = "cn-zh"
enableEmoji = true
enableRobotsTXT = true
languageCode = "cn-zh"
# Choose one of emacs, trac or perldoc, monokai
pygmentsStyle = "dracula"
theme = "gokarna"
title = "Hindung's Blog"

[params]
  avatarAltText = "avatar"
  avatarSize = "size-m"
  avatarURL = "https://github.com/hindungWang.png"

  description = "‚úèÔ∏èÁΩëÁªúÁ¨îËÆ∞üìí"
  footer = "HindungWang"
  metaKeywords = ["blog", "gokarna", "hugo"]
  showBackToTopButton = true # true or false for "back to top" button on posts and pages

  socialIcons = [
    {name = "twitter", url = "https://example.com"},
    {name = "linkedin", url = "https://example.com"},
    {name = "stackoverflow", url = "https://example.com"},
    {name = "dribbble", url = "https://example.com"},
    {name = "instagram", url = "https://example.com"},
    {name = "twitch", url = "https://example.com"},
    {name = "email", url = "mailto:example@example.com"}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "About"
    pre = "<span data-feather='home'></span>"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='page'></span>"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/gokarna-theme/gokarna-hugo"
    weight = 5

  [[menu.main]]
    identifier = "buymeacoffee"
    pre = "<span data-feather='coffee'></span>"
    url = "https://buymeacoffee.com/hindung"
    weight = 6

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 7

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[minify]
    minifyOutput = true
