baseUrl: http://hindung.cn/
languageCode: en-us
theme: terminal
paginate: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: green
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 4
  # show selector to switch language
  showLanguageSelector: true
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: true
  toc: true
  readingTime: true

languages:
  en:
    languageName: English
    title: Hindung Blogs
    subtitle: 部落格
    keywords: ''
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: Hindung
        logoHomeLink: /

    menu:
      main:
      - identifier: about
        name: About
        url: /about
      - identifier: post
        name: Post
        url: /posts
